type Country = {
    name: {
      common: string,
      official: string,
      nativeName: { [key: string]: { official: string } }
    },
    tld: string[],
    cca2: string,
    ccn3: string,
    cca3: string,
    cioc?: string,
    independent: boolean,
    status: string,
    unMember: boolean,
    currencies: { [code: string]: { name: string, symbol: string } },
    idd: { root: string, suffixes: string[] },
    capital?: string[],
    altSpellings: string[],
    region: string,
    subregion: string,
    languages: { [code: string]: string },
    translations: { [code: string]: { official: string, common: string } },
    latlng: number[],
    landlocked: boolean,
    borders: string[],
    area: number,
    demonyms: { [key: string]: { f: string, m: string } },
    flag: string,
    maps: { [key: string]: string },
    population: number,
    flags: string[],
    timezones: string[],
    continents: string[],
    flagsEmoji: string,
    ciocCurrency: string,
    ciocMerged?: string[],
    ciocWhitelist?: string[]
  }
  